### ISSUE TITLE
Needed to move -lbz2 to end of linker command (on Ubuntu 14.04.2)

### ISSUE THREAD

**Issue by pfh** [timmassingham/CifTools#2]
I needed to modify the Makefile in order to compile ciftools, putting the libraries at the end in the linker step.

eg

```
cifinfo: $(objects) cifinfo.o
    $(CC) $(CFLAGS) $(DEFINES) $(INCFLAGS) -o ../bin/$@ $(LDFLAGS) $^
```

becomes:

```
cifinfo: $(objects) cifinfo.o
    $(CC) $(CFLAGS) $(DEFINES) $(INCFLAGS) -o ../bin/$@ $^ $(LDFLAGS)
```

I'm not sure why this is necessary. (I googled the error message and found this: https://bugs.launchpad.net/ubuntu/+source/bsdiff/+bug/726338 , comment #2 suggested the fix.)

**Comment by timmassingham** [comment]
Thanks, now fixed.
